### ISSUE TITLE
one question about getionimage method

### ISSUE THREAD

**Issue by inaciomdrs** [alexandrovteam/pyimzML#35]
Why the "number of pixels" in matrix returned from getionimage method is not the same of the number of coordinates from ImzMLParser?

**Comment by inaciomdrs** [comment]
I'm in contact with my collaborators to get permission to share. Meanwhile, for the files I'm the currently working on, while the number of coordinates from imzML is ~50k, the number of pixels in matrix from getionimage is (a little) more than 60k. This issue also in another imzML, which has 136 coordinates, but the matrix from getionimage has 792 pixels.

**Comment by theodev** [comment]
@inaciomdrs it's hard to say without seeing your file. Please check, maybe your imzML file was acquired not from a rectangular region but from a custom region of interest. Then this can explain the difference between the number of acquired pixels and the number of pixels in the bounding-box image

**Comment by inaciomdrs** [comment]
I have just discovered that the imzML is publicly available. The download link follows below:

https://massive.ucsd.edu/ProteoSAFe/dataset_files.jsp?task=71cb99301a5b445dafb5e8eddccfdbe1#%7B%22table_sort_history%22%3A%22main.collection_asc%22%7D

**Comment by inaciomdrs** [comment]
> @inaciomdrs it's hard to say without seeing your file. Please check, maybe your imzML file was acquired not from a rectangular region but from a custom region of interest. Then this can explain the difference between the number of acquired pixels and the number of pixels in the bounding-box image

Great point. I have a big suspection that this happened.

**Comment by sergii-mamedov** [comment]
@inaciomdrs Unfortunately, I do not have access to these files because it has been a long time.

However, I have examined several datasets that have non rectangular shape. `ImzMLParser.coordinates` returns a list of real pixels for which spectra are available. Instead, the `getionimage` function returns a rectangular image that covers all pixels with spectra. We create a 2D array with the number of pixels on the X axis as `max count of pixels x` and the same for Y. Code example from the function:
```
im = np.zeros((p.imzmldict["max count of pixels y"], p.imzmldict["max count of pixels x"]))
```

You can check it on [one of the public dataset](https://metaspace2020.eu/dataset/2024-02-15_23h57m39s):
1. ImzMLParser.coordinates = 24488 pixels
2. getionimage - ndarray: (281, 113) = 31753 pixels

**Comment by inaciomdrs** [comment]
Understood, thank you very much @sergii-mamedov. I ended up moving out of the project. In any case, this is a very important clarification.

**Comment by sergii-mamedov** [comment]
@inaciomdrs Once again, I apologize for the long answer. Get in touch if you have any other questions.
